src/Entity/Employe.php
<?php

namespace App\Entity;

use App\Repository\EmployeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmployeRepository::class)]
class Employe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateNaissance = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateEmbauche = null;

    #[ORM\Column(length: 50)]
    private ?string $ville = null;

    #[ORM\ManyToOne(inversedBy: 'employes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Entreprise $entreprise = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $dateNaissance): static
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getDateEmbauche(): ?\DateTimeInterface
    {
        return $this->dateEmbauche;
    }

    public function setDateEmbauche(\DateTimeInterface $dateEmbauche): static
    {
        $this->dateEmbauche = $dateEmbauche;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): static
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getAge()
    {
        $now = new \DateTime();
        $interval = date_diff($this->dateNaissance, $now);
        return $interval->format("%Y");
    }

    public function __toString()
    {
        return $this->prenom . " " . $this->nom; 
    }
}

src/Form/EmployeType.php
<?php

namespace App\Form;

use App\Entity\Employe;
use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class EmployeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('prenom', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('dateNaissance', DateType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('dateEmbauche', DateType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('ville', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('entreprise', EntityType::class, [
                'class' => Entreprise::class,
                'choice_label' => 'raisonSociale',
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('submit', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-secondary'
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Employe::class,
        ]);
    }
}

src/Controller/EmployeController.php
<?php

namespace App\Controller;

use App\Entity\Employe;
use App\Form\EmployeType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EmployeController extends AbstractController
{
    #[Route('/employe', name: 'app_employe')]
    public function index(ManagerRegistry $doctrine): Response
    {
        // récupérer toutes les employes de la BDD        Pour trier les noms par ordre alphabetique on utilise findBy et on met un paramètre le premier tableau vide( des employés) puis le nom ou sinon on peut demander à sortir que ceux qui sont de Strasbourg ça fait comme une requete SQL  SELECT * FROM employe WHERE ville = Strasbourg ORDER BY nom ASC
        $employes = $doctrine->getRepository(Employe::class)->findAll([], ["nom" => "ASC"]);
        // $employes = $doctrine->getRepository(Employe::class)->findBy(["ville" => "Strasbourg"], ["nom" => "ASC"]);
        return $this->render('employe/index.html.twig', [
            'employes' => $employes
        ]);
    }


    #[Route('/employe/add', name: 'add_employe')]
    #[Route('/employe/{id}/edit', name: 'edit_employe')]
    public function add(ManagerRegistry $doctrine, Employe $employe = null, Request $request): Response
    {

        if(!$employe) {
            $employe = new Employe();
        }

        $form = $this->createForm(EmployeType::class, $employe);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $employe = $form->getData();
            $entityManager = $doctrine->getManager();
            //equivalent prepare request pour éviter les failles SQL
            $entityManager->persist($employe);
            // insert into (execute)
            $entityManager->flush();

            return $this->redirectToRoute('app_employe');
        }
        //vue pour affiche le formaulaire d'ajout 
        return $this->render('employe/add.html.twig', [
            'formAddEmploye' => $form->createView(),
            'edit' => $employe->getId(),
        ]);
    }


    #[Route('/employe/{id}/delete', name: 'delete_employe')]
    public function delete(ManagerRegistry $doctrine, Employe $employe): Response
    {
        $entityManager = $doctrine->getManager();
        $entityManager->remove($employe);
        $entityManager->flush();

        return $this->redirectToRoute('app_employe');
    }


    #[Route('/employe/{id}', name: 'show_employe')]
    public function show(Employe $employe): Response
    {
        return $this->render('employe/show.html.twig', [
            'employe' => $employe
        ]);
    }
}

templates/employe/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EmployeController!{% endblock %}

{% block body %}
    
    {% if edit %}
        <h1>Editer un employé</h1>
    {% else %}
        <h1>Ajouter un employé</h1>
    {% endif %}


    {# {{ form(formAddEmploye) }} #}


    {{ form_start(formAddEmploye) }}

    <div class="nomPrenom">
        {{ form_row(formAddEmploye.nom) }}
        {{ form_row(formAddEmploye.prenom) }}
    </div>
    <div>
        {{ form_row(formAddEmploye.dateNaissance) }}
        {{ form_row(formAddEmploye.dateEmbauche) }}
        {{ form_row(formAddEmploye.ville) }}
        {{ form_row(formAddEmploye.entreprise) }}
        {{ form_row(formAddEmploye.submit) }}
    </div>

    {{ form_end(formAddEmploye) }}


{% endblock %}

templates/employe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EmployeController!{% endblock %}

{% block body %}
    <h1>liste des employés :</h1>

    <a class="btn btn-primary" href="{{ path('add_employe') }}"> Ajouter un employé</a><br> 


    {% for employe in employes %}
    {# Différentes facon de faire la premiere avec concaténation " ~ " / la deuxieme en ouvrant à chaque fois les " {{}} " et la troisième avec le __toString  #}
    {# {{employe.raisonSociale ~ ' (' ~ employe.cp ~ ' ' ~ employe.ville ~ ')'}} <br> #}
    {# {{ employe.raisonSociale }} ({{ employe.cp }} {{ employe.ville }}) <br> #}

    <a href="{{ path('show_employe', {'id': employe.id}) }}">{{ employe }} </a> <br>
    <a class="btn btn-warning" href="{{ path('edit_employe', {'id': employe.id}) }}">Edit</a>
    <a class="btn btn-danger" href="{{ path('delete_employe', {'id': employe.id}) }}">Remove</a> <br>


{% endfor %}
{% endblock %}

templates/employe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'un employé{% endblock %}

{% block body %}
    <h1>{{ employe}}</h1>
    <p>
        ville : {{ employe.ville }} <br>
        Entreprise : <a href="{{ path('show_entreprise', {'id': employe.entreprise.id})}}">{{ employe.entreprise }}</a> <br>
        Date d'embauche : {{ employe.dateEmbauche | date('d-m-Y') }} <br>
        Date de naissance : {{ employe.dateNaissance | date('d-m-Y') }} ({{ employe.age }} ans) <br>
    </p>
    
{% endblock %}